// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/04/2025, 17.35.49
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["M:/github/dmxsan.github.io/components/**/*.{vue,js,jsx,mjs,ts,tsx}","M:/github/dmxsan.github.io/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","M:/github/dmxsan.github.io/components/**/*.{vue,js,jsx,mjs,ts,tsx}","M:/github/dmxsan.github.io/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","M:/github/dmxsan.github.io/plugins/**/*.{js,ts,mjs}","M:/github/dmxsan.github.io/composables/**/*.{js,ts,mjs}","M:/github/dmxsan.github.io/utils/**/*.{js,ts,mjs}","M:/github/dmxsan.github.io/pages/blog.vue","M:/github/dmxsan.github.io/pages/blog/[slug].vue","M:/github/dmxsan.github.io/pages/about.vue","M:/github/dmxsan.github.io/pages/index.vue","M:/github/dmxsan.github.io/pages/projects.vue","M:/github/dmxsan.github.io/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","M:/github/dmxsan.github.io/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","M:/github/dmxsan.github.io/app.config.{js,ts,mjs}","M:/github/dmxsan.github.io/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;